// Manifest-to-load reconciliation (#255 review, item 4). Every entry of the last
// manifest is classified exactly once: loaded into a named table, intentionally
// not loaded for a reason the maintainer decided (2026-10-06, ADR-0013 §1), or
// UNMAPPED. The job refuses to load while any entry is unmapped, so a store the
// transform never heard of cannot vanish without trace. Names are the manifest's
// own relative paths inside the v1 data directory; nothing here is a location.

import type { ArchiveManifest } from './archive-manifest.js';

export type NotLoadedReason =
  'live-side' | 'lease/lock/archive-state' | 'superseded' | 'evidence-frozen';

export const NOT_LOADED_REASONS: ReadonlyArray<NotLoadedReason> = [
  'live-side',
  'lease/lock/archive-state',
  'superseded',
  'evidence-frozen',
];

export interface LoadedEntry {
  path: string;
  /** The `engine` table(s) the file's rows went to. */
  tables: string[];
}

export interface NotLoadedEntry {
  path: string;
  reason: NotLoadedReason;
  note: string;
}

export interface ManifestClassification {
  manifestFiles: number;
  loaded: LoadedEntry[];
  notLoaded: NotLoadedEntry[];
  unmapped: string[];
  /** Loaded + not loaded + unmapped; equals `manifestFiles` by construction. */
  classified: number;
}

/**
 * What the transform knows about the tree it consumed, recorded while the plan
 * was built so the classification cannot disagree with the load.
 */
export interface ConsumptionRecord {
  /** Files the plan read, with the tables their rows went to. */
  consumed: Map<string, Set<string>>;
  /** Evidence batch files referenced by at least one paper order (loaded). */
  paperBatchFiles: Set<string>;
  /** Evidence batch files referenced only by live orders (dropped at the seam). */
  liveOnlyBatchFiles: Set<string>;
  /** Forecast shard-directory files the current index names (loaded). */
  currentForecastFiles: Set<string>;
}

const EVIDENCE_DIRECTORY = 'execution-order-evidence/';
const FORECAST_DIRECTORY = 'forecast-history-shards/';

const LIVE_SIDE_FILES = new Set([
  'live-skips.json',
  'live-skips.journal.jsonl',
  'kalshi-reconciliation-checkpoint.json',
]);

/** Derived, rebuildable or retired stores (sanitized inventory B.1: 3, 10, 22, 25, 27). */
const SUPERSEDED_FILES = new Map<string, string>([
  ['forecast-history.json', 'legacy v2 snapshot superseded by storage v4 shards'],
  ['regime-gate.json', 'derived control, regenerated by the new engine'],
  ['cycle-paths.json', 'derived report input, regenerated by the new engine'],
  ['paper-fill-calibration.json', 'configuration re-entered by hand in the new system'],
]);

const base = (path: string) => path.slice(path.lastIndexOf('/') + 1);

/** Quarantine and migration copies the v1 writer kept beside a store. */
function isQuarantineCopy(path: string): boolean {
  const name = base(path);
  return /\.corrupt-/.test(name) || /\.superseded-/.test(name) || name.endsWith('.journal-copy');
}

function isLeaseOrState(path: string): boolean {
  if (base(path) === 'archive-state.json') return true;
  return path.split('/').some((part) => part.endsWith('.lock') || part.endsWith('.lock/'));
}

export function classifyManifest(
  manifest: Pick<ArchiveManifest, 'files'>,
  record: ConsumptionRecord,
): ManifestClassification {
  const loaded: LoadedEntry[] = [];
  const notLoaded: NotLoadedEntry[] = [];
  const unmapped: string[] = [];
  const seen = new Set<string>();

  const skip = (path: string, reason: NotLoadedReason, note: string) =>
    notLoaded.push({ path, reason, note });

  for (const file of [...manifest.files].sort((a, b) => (a.path < b.path ? -1 : 1))) {
    const path = file.path;
    if (seen.has(path)) continue;
    seen.add(path);

    const tables = record.consumed.get(path);
    if (tables && tables.size > 0) {
      loaded.push({ path, tables: [...tables].sort() });
      continue;
    }
    if (isLeaseOrState(path)) {
      skip(path, 'lease/lock/archive-state', 'leases, locks and archive state never migrate');
      continue;
    }
    if (LIVE_SIDE_FILES.has(path)) {
      skip(path, 'live-side', 'live-side store dropped at the paper seam');
      continue;
    }
    if (path.startsWith(EVIDENCE_DIRECTORY)) {
      if (record.liveOnlyBatchFiles.has(path)) {
        skip(path, 'live-side', 'evidence batch referenced only by live orders');
      } else {
        skip(
          path,
          'evidence-frozen',
          'evidence batch no ledger order references; frozen in the archive',
        );
      }
      continue;
    }
    if (path.startsWith('execution-ledger-legacy/')) {
      skip(path, 'superseded', 'pre-v9 ledger copy; the v9 ledger is loaded instead');
      continue;
    }
    if (path.startsWith(FORECAST_DIRECTORY)) {
      // Every file the current index names was consumed above; the rest belong
      // to an earlier sealed generation the index no longer references.
      skip(path, 'superseded', 'forecast artifact of a generation the current index does not name');
      continue;
    }
    if (isQuarantineCopy(path)) {
      skip(path, 'superseded', 'quarantine or migration copy kept beside its store');
      continue;
    }
    const supersededNote = SUPERSEDED_FILES.get(path);
    if (supersededNote) {
      skip(path, 'superseded', supersededNote);
      continue;
    }
    unmapped.push(path);
  }

  return {
    manifestFiles: manifest.files.length,
    loaded,
    notLoaded,
    unmapped,
    classified: loaded.length + notLoaded.length + unmapped.length,
  };
}

export function countByReason(entries: NotLoadedEntry[]): Record<NotLoadedReason, number> {
  const counts = Object.fromEntries(NOT_LOADED_REASONS.map((r) => [r, 0])) as Record<
    NotLoadedReason,
    number
  >;
  for (const entry of entries) counts[entry.reason] += 1;
  return counts;
}
