import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import postcss from 'postcss';
import tailwindcss from '@tailwindcss/postcss';

const root = process.cwd();
const source = path.join(root, 'src/app/globals.source.css');
const output = path.join(root, 'src/app/globals.css');
const generatedHeader = '/* Generated by scripts/build-tailwind-css.ts. Edit src/app/globals.source.css instead. */\n';

async function main() {
  const css = await readFile(source, 'utf8');
  const result = await postcss([
    tailwindcss({ base: root, optimize: process.env.NODE_ENV === 'production' }),
  ]).process(css, { from: source, to: output });
  await writeFile(output, `${generatedHeader}${result.css}`);
  console.log(`Generated ${path.relative(root, output)} from ${path.relative(root, source)}`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
